@echo off

set REPOSITORY_EXECUTABLE=hexray-gpu.exe
set REPOSITORY_ROOT_DIR=%~dp0..
set REPOSITORY_ORIGINAL_SCENE_DIR=%REPOSITORY_ROOT_DIR%\original_scenes
set REPOSITORY_SCENE_DIR=%REPOSITORY_ROOT_DIR%\scenes

set ORIGINAL_HEXRAY_EXECUTABLE=hexray.exe
set ORIGINAL_HEXRAY_REPOSITORY_ROOT_DIR=D:\SU\II\Raytrace\Repo
set ORIGINAL_HEXRAY_SCENE_DIR=%ORIGINAL_HEXRAY_REPOSITORY_ROOT_DIR%\data

set REPOSITORY_EXECUTABLE_PATH=%REPOSITORY_ROOT_DIR%\bin\Debug\%REPOSITORY_EXECUTABLE%
set ORIGINAL_HEXRAY_EXECUTABLE_PATH=%ORIGINAL_HEXRAY_REPOSITORY_ROOT_DIR%\Build\RelWithDebInfo\%ORIGINAL_HEXRAY_EXECUTABLE%
